services:
  zull:
    container_name: zull
    image: zull:latest
    environment:
      - TZ=America/Guayaquil
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
    ports:
      - 8713:8713

    volumes:
      - /origamigt_archivo/:/origamigt_archivo/
    networks:
      - default

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
