services:
  app:
    image: config-server
    container_name: ${DOCKER_CONTAINER_NAME}
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=America/Guayaquil
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI_GIT}
      - SPRING_CLOUD_CONFIG_PASSWORD=${SPRING_CLOUD_CONFIG_PASSWORD}
    volumes:
      - /origamigt_archivo/:/origamigt_archivo/
    ports:
      - 8888:8888

