version: "2"
services:
  correo:
    container_name: correo
    image: correo:latest
    environment:
      - TZ=America/Guayaquil
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
    ports:
      - 8715:8715

    volumes:
      - /origamigt_archivo/:/origamigt_archivo/
    networks:
      - default

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
