version: "2"
services:
  media:
    container_name: media
    image: media:latest
    environment:
      - TZ=America/Guayaquil
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
    ports:
      - 8720:8720

    volumes:
      - /origamigt_archivo/:/origamigt_archivo/
    networks:
      - default

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
