version: "2"
services:
  documental:
    container_name: documental
    image: documental:latest
    environment:
      - TZ=America/Guayaquil
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_CLOUD_CONFIG_URI=${SPRING_CLOUD_CONFIG_URI}
    ports:
      - 8718:8718

    volumes:
      - /origamigt_archivo/:/origamigt_archivo/
    networks:
      - default

networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
